//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public decimal AccessLevelId { get; set; }
        public decimal AccessId { get; set; }
    
        public virtual AccessLevel AccessLevel { get; set; }
    }
}
