//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITY()
        {
            this.SHAREHOLDERs = new HashSet<SHAREHOLDER>();
        }
    
        public decimal CITYID { get; set; }
        public Nullable<decimal> STATEID { get; set; }
        public string USER_ID { get; set; }
        public string DESC1 { get; set; }
        public string CITY_TEL_CODE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string MAP_CODE { get; set; }
        public string MAP_IDENTITY { get; set; }
        public Nullable<int> MAP_X { get; set; }
        public Nullable<int> MAP_Y { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHAREHOLDER> SHAREHOLDERs { get; set; }
    }
}
