//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryAndExitLog
    {
        public decimal Id { get; set; }
        public decimal UserId { get; set; }
        public string Type { get; set; }
        public System.DateTime PersistOnDate { get; set; }
        public string Long { get; set; }
        public string Lat { get; set; }
        public string DeviceType { get; set; }
        public string BrowserType { get; set; }
        public string OsType { get; set; }
        public string Ip { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
