//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_YEAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIN_YEAR()
        {
            this.SHR_FIN_INFO = new HashSet<SHR_FIN_INFO>();
        }
    
        public string FIN_YEAR_CODE { get; set; }
        public string SHR_MEET_KIND { get; set; }
        public string SHR_MEET_DATE { get; set; }
        public string USER_ID { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string YEAR_SITU { get; set; }
        public Nullable<decimal> FIRST_DOC_NO { get; set; }
        public string SHR_PROFIT_COND { get; set; }
        public string TAX_FLAG { get; set; }
        public string DED_FLAG { get; set; }
        public Nullable<decimal> DPS { get; set; }
        public Nullable<decimal> EPS { get; set; }
        public Nullable<decimal> PEPS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHR_FIN_INFO> SHR_FIN_INFO { get; set; }
    }
}
