//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lock
    {
        public string DeviceId { get; set; }
        public string CustomerName { get; set; }
        public decimal Id { get; set; }
        public string ValidDate { get; set; }
    }
}
