//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareholderWatch
    {
        public decimal Id { get; set; }
        public decimal UserId { get; set; }
        public string Title { get; set; }
        public string Desc1 { get; set; }
        public string WatchList { get; set; }
        public bool IsDefault { get; set; }
        public bool IsPublic { get; set; }
        public System.DateTime PersistOnDate { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
