//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHR_FIN_INFO
    {
        public string SHRH_CODE { get; set; }
        public decimal SFINF_ROW { get; set; }
        public string FIN_YEAR_CODE { get; set; }
        public string SHR_OPR_CODE { get; set; }
        public string USER_ID { get; set; }
        public string CAP_DATE { get; set; }
        public string TBL_DATE { get; set; }
        public decimal AMNT { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string doc_no { get; set; }
        public string doc_date { get; set; }
        public string note { get; set; }
    
        public virtual FIN_YEAR FIN_YEAR { get; set; }
        public virtual SHAREHOLDER SHAREHOLDER { get; set; }
    }
}
