//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHR_TRANSACTION
    {
        public decimal TRNS_NO { get; set; }
        public string AGNT_CODE { get; set; }
        public string SHRH_CODE { get; set; }
        public string USER_ID { get; set; }
        public string SHA_SHRH_CODE { get; set; }
        public string AGE_AGNT_CODE { get; set; }
        public string TBL_DATE { get; set; }
        public long SHR_QUNT { get; set; }
        public Nullable<decimal> AMNT { get; set; }
        public string TRNS_KIND { get; set; }
        public string TRNS_SHR_KIND { get; set; }
        public string TRNS_DOC_CODE { get; set; }
        public string TRNS_DOC_DATE { get; set; }
        public string TRNS_OK { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string SHR_FLAG { get; set; }
        public string NOTE { get; set; }
        public string trns_flag { get; set; }
        public string FIN_YEAR_CODE { get; set; }
        public Nullable<decimal> DOC_NO { get; set; }
    
        public virtual SHAREHOLDER SHAREHOLDER { get; set; }
        public virtual SHAREHOLDER SHAREHOLDER1 { get; set; }
    }
}
