//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    
    public partial class sp_shr_rpt_05_dashboard_Result3
    {
        public string col1 { get; set; }
        public Nullable<decimal> sort_col { get; set; }
        public string shrh_kind { get; set; }
        public Nullable<decimal> sum_shrh { get; set; }
    }
}
