//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    
    public partial class sp_shr_seller_buyer_dashboard_Result1
    {
        public string seller_cnt { get; set; }
        public Nullable<decimal> seller_sumshare { get; set; }
        public Nullable<decimal> seller_amnt { get; set; }
        public string fullname { get; set; }
        public string buyer_cnt { get; set; }
        public string SHRH_CODE { get; set; }
        public Nullable<decimal> buyer_sumshare { get; set; }
        public Nullable<decimal> buyer_amnt { get; set; }
        public Nullable<decimal> buy_fee_avg { get; set; }
        public Nullable<decimal> sell_fee_avg { get; set; }
        public Nullable<decimal> result { get; set; }
    }
}
