//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_fb_shr_shrh_info
    {
        public string shrh_code { get; set; }
        public Nullable<long> share { get; set; }
        public decimal sum_mone { get; set; }
        public string pkey_shrh_code { get; set; }
    }
}
