//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_fb_shr_shrh_sum
    {
        public string shrh_code { get; set; }
        public decimal cur_profit_amnt { get; set; }
        public decimal cur_cap_amnt { get; set; }
        public decimal cur_pri_amnt { get; set; }
        public string cur_year { get; set; }
        public decimal last_amnt { get; set; }
        public string last_date { get; set; }
        public decimal last_amnt1 { get; set; }
        public Nullable<long> share { get; set; }
        public string last_tr_date { get; set; }
        public long cap_qunt { get; set; }
    }
}
